# Generated by Django 3.2.8 on 2021-10-12 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KrakenSymbols',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_name', models.CharField(max_length=40)),
                ('coin_symbol', models.CharField(max_length=10)),
                ('currency', models.CharField(choices=[('USD', 'US dollar'), ('GBP', 'British pound'), ('EUR', 'Euro'), ('JPY', 'Japanese Yen')], max_length=3)),
                ('symbol', models.CharField(max_length=13, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='KrakenOHLC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open', models.DecimalField(decimal_places=2, max_digits=11)),
                ('high', models.DecimalField(decimal_places=2, max_digits=11)),
                ('low', models.DecimalField(decimal_places=2, max_digits=11)),
                ('close', models.DecimalField(decimal_places=2, max_digits=11)),
                ('date', models.DateField()),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_OHLC', to='crypto_data.krakensymbols')),
            ],
        ),
    ]
